# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\"E\n\x06vidMsg\x12\x19\n\x05\x66rame\x18\x01 \x01(\x0b\x32\n.frameData\x12\x12\n\nparameters\x18\x02 \x03(\x05\x12\x0c\n\x04info\x18\x03 \x03(\t\"3\n\tframeData\x12\x12\n\nframeShape\x18\x01 \x03(\x05\x12\x12\n\nframeBytes\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDMSG']._serialized_start=13
  _globals['_VIDMSG']._serialized_end=82
  _globals['_FRAMEDATA']._serialized_start=84
  _globals['_FRAMEDATA']._serialized_end=135
# @@protoc_insertion_point(module_scope)
